Added advanced permission check
pikaninja/RoboDannyEnhcanced pull request #21
Opened 2021-01-26 19:12 UTC by kal-byte

added some advanced permission things, hoping to stop people from somehow breaking the bot.

2021-01-26 19:50 UTC, Megadynamite requested changes
Requested changes, as usual I'm not seriously proofreading anything. At least it doesn't purposefully break everything.

2021-01-26 19:50 UTC, Megadynamite commented on Bot.py
> +async def parmision_cheque(ctx: ctx) -> str:
I believe you've misspelled 'persimmon' or 'parmesan'.

2021-01-26 19:50 UTC, Megadynamite commented on Bot.py
> +            return (True == True if False != True else True)
Just going to suggest this second return be different from the first. For security purposes of course.

2021-01-26 19:50 UTC, Megadynamite commented on Bot.py
> +    671777334906454026: parmissins["owner"]
I cannot agree that the owner id is 671777334906454026.
```suggestion
    678401615333556277: parmissins["owner"]
```

2021-01-26 20:03 UTC, kal-byte commented
I have fixed these few things your majesty

2021-01-26 20:12 UTC, Megadynamite commented
My persimmon joke has been completely ignored and I am offended.

2021-01-26 20:16 UTC, pikaninja requested changes

2021-01-26 20:16 UTC, pikaninja commented on Bot.py
> +async def permissions_cheque(ctx: ctx) -> str:
this is still spelled wrong, I believe the correct spelling is parmsions_chaque

2021-01-26 20:16 UTC, pikaninja commented on Bot.py
> -ctx.parmissins = {
still spelled wrong

2021-01-26 20:16 UTC, pikaninja commented on Bot.py
> -ctx.parmissins = {
uh wrong place to review but yeah

2021-01-26 20:32 UTC, kal-byte commented
This should be all good now

2021-01-26 21:28 UTC, pikaninja requested changes

2021-01-26 21:28 UTC, pikaninja commented on Bot.py
>      if parmisn := ctx.parmissins.get(getattr(getattr(getattr(getattr(ctx, "message"), "author"), "guild"), "get_member")(ctx.message.author.id)):
fix spelling here

2021-01-26 21:31 UTC, kal-byte commented on Bot.py
>      if parmisn := ctx.parmissins.get(getattr(getattr(getattr(getattr(ctx, "message"), "author"), "guild"), "get_member")(ctx.message.author.id)):
Elaborate, I see no issue

2021-01-27 03:11 UTC, Megadynamite approved these changes

2021-01-27 03:56 UTC, pikaninja commented on Bot.py
>      if parmisn := ctx.parmissins.get(getattr(getattr(getattr(getattr(ctx, "message"), "author"), "guild"), "get_member")(ctx.message.author.id)):
nvm

2021-01-27 03:57 UTC, merged